---
# tasks file for ossec-webui
- name: Install apache php
  yum: state=latest name={{ item }}
  with_items:
    - httpd
    - php
    - php-fpm
    - php-common

- name: add user apache to ossec group
  user:
    name: apache
    groups: ossec
    append: yes



- name: download ossec-wui
  get_url:
    url: https://github.com/ossec/ossec-wui/archive/0.9.tar.gz
    dest: /root/0.9.tar.gz


- name: extract ossec-wui
  unarchive:
    src=/root/0.9.tar.gz
    dest=/var/www/html/
    creates=/var/www/html/ossec-wui-0.9
    copy=no
  notify: start httpd


- name: create directory ossec-wui for targeted selinux
  file:
    path: /etc/selinux/targeted/ossec-wui
    state: directory


- name: copy ossec-wui targeted policy for selinux
  copy:
    src: files/ossec-wui.te
    dest: /etc/selinux/targeted/ossec-wui/ossec-wui.te

- name: checkmodule ossec-wui for selinux
  command: checkmodule -M -m ossec-wui.te -o ossec-wui.mod
  args:
    chdir: /etc/selinux/targeted/ossec-wui

- name: semodule_package ossec-wui for selinux
  command: semodule_package -o ossec-wui.pp -m ossec-wui.mod
  args:
    chdir: /etc/selinux/targeted/ossec-wui

- name: semodule ossec-wui for selinux
  command: semodule -i ossec-wui.pp
  args:
    chdir: /etc/selinux/targeted/ossec-wui

- name: disable selinux
  selinux:
    state: disabled
